In [2]:
import numpy as np

In [2]:
np.zeros(2)

array([0., 0.])

In [3]:
np.ones(2)

array([1., 1.])

In [3]:
np.empty(2)

array([ 6.33613991e+307, -2.83989685e-190])

In [5]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [6]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [6]:
np.linspace(0,10,num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
x=np.ones(2,dtype=np.float64)
x

array([1., 1.])

In [9]:
arr=np.array([4,6,3,2,5,9])
val=np.sort(arr)
val

array([2, 3, 4, 5, 6, 9])

we will create the 2-d array

In [10]:
x=np.array([[1,2,3],[4,5,6]])
x

array([[1, 2, 3],
       [4, 5, 6]])

creating the 3-d arrray which will be containing the 2 2-d array as their element

In [11]:
x=np.array([[[2,3,4],[6,7,8]],[[4,5,8],[5,9,8]]])
x

array([[[2, 3, 4],
        [6, 7, 8]],

       [[4, 5, 8],
        [5, 9, 8]]])

to know how many dimensions does array holds we need to use the attribute called ndim


In [12]:
x=np.array([[[2,3,4],[6,7,8]],[[4,5,8],[5,9,8]]])
x.ndim

3

to convert the given array into n dimensions we use the ndmin=n where n=0,1,2,3.... 

In [13]:
x=np.array([[[2,3,4],[6,7,8]],[[4,5,8],[5,9,8]]],ndmin=5)
print(x)
'number of dimensions are',x.ndim

[[[[[2 3 4]
    [6 7 8]]

   [[4 5 8]
    [5 9 8]]]]]


('number of dimensions are', 5)

array slicing

In [14]:
x=np.array([1,2,3,4,5,6,7,8,9])
print(x[1:5])

[2 3 4 5]


slicing without worrying about the starting or the ending index

In [15]:
x=np.array([1,2,3,4,5,6,7,8,9])
print(x[:7])
print(x[2:])

[1 2 3 4 5 6 7]
[3 4 5 6 7 8 9]


now slicing by jumping steps ahead 

In [16]:
x=np.array([1,2,3,4,5,6,7,8,9])
print(x[1:5:2])
print(x[::2])

[2 4]
[1 3 5 7 9]


slicing in 2-d array
q1-print 5,6

In [17]:
x=np.array([[1,2,3],[4,5,6]])
print(x[1,1:3])


[5 6]


example to print the  1st four elements of the both single array of 2-d array

In [9]:
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(x[0:3,0:2])

[[1 2]
 [4 5]
 [7 8]]


data types in python 

In [19]:
x=np.array([1,2,3,4,5,6,7,8,9],dtype='S')
print(x)
print(x.dtype)

[b'1' b'2' b'3' b'4' b'5' b'6' b'7' b'8' b'9']
|S1


now we will create an array with data type of 4 byte int

In [11]:
x=np.array([1,2,3,4,5,6,7,8,9],dtype='i4')
print(x)
print(x.dtype)

[1 2 3 4 5 6 7 8 9]
int32


to convert the given array into another type using astype()

In [12]:
x=np.array([1.1,1.2,1.3])
print(x.dtype)
y=x.astype('i')
print(y)
print(y.dtype)


float64
[1 1 1]
int32


copy v/s view in numpy array
copy will create a copy of the existing array and we can update the values of the copied array without changing in actual arrray

but in view is depend on the parent array so changes made in view array also affect the parent array



In [22]:
x=np.array([1,2,3,4,5,6,7,8,9])
y=x.copy()
y[0]=42
print(x)
print(y)

[1 2 3 4 5 6 7 8 9]
[42  2  3  4  5  6  7  8  9]


In [23]:
x=np.array([1,2,3,4,5,6,7,8,9])
y=x.view()
x[0]=42
print(x)
print(y)

[42  2  3  4  5  6  7  8  9]
[42  2  3  4  5  6  7  8  9]


shape of an array->it is the number of elements in each dimensions
where the first value in output represents the dimension and second value means elements in each 

In [24]:
x=np.array([[1,2,3],[4,5,6]])
print(x.shape)

(2, 3)


example-: here we will create an array of dimenstion 5 and then try to find the shape of the array

In [25]:
x=np.array([1,2,3,4,5,6,7,8,9],ndmin=5)
print(x)
print('shape of the array is',x.shape)


[[[[[1 2 3 4 5 6 7 8 9]]]]]
shape of the array is (1, 1, 1, 1, 9)


in above output the 1,1,1,1 represents the dim-5 contains 1 ele,dim-4 contains 1 ele,dim-3 contains 1,dim-2 contains 1 ele,but dim-1 contains 9 ele

Reshaping of the array
note: reshape() is the view type attribute that means it changes the origional array we can check this by using .base

converting the array 1-d into 2-d
where in reshape(partition,elements)

In [26]:
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(x.reshape(4,3))
print(x.reshape(2,6).base)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


converting the array 1-d into 3-d

In [27]:
x=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
y=x.reshape(2,3,2)
print(y)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [28]:
x=np.array([1,2,3,4,5,6,7,8])
y=x.reshape(2,2,2)
print(y)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


default computation of the reshaping elements
reshape(2,2,-1) the value -1 is the unknown and we want to divide the element into 2 major parts which contains 2-2 sub parts each but we want to let compiler do the rest job of finding how many element does these sub parts should contains

In [29]:
x=np.array([1,2,3,4,5,6,7,8])
y=x.reshape(2,2,-1)
print(y)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


iterating in 2-d array
in below type of iterating this loop will iterate to each particular index and print all elements inside it

In [30]:
x=np.array([[1,2,3],[4,5,6]])
for i in x:
    print(i)

[1 2 3]
[4 5 6]


to iterate on each scalar element of the 2-d array

In [31]:
x=np.array([[1,2,3],[4,5,6]])
for i in x:
    for j in i:
        print(j)


1
2
3
4
5
6


iterating arrray using the nditer() function 
now we will iterate on each scalar element

In [32]:
x=np.array([[[2,3,4],[6,7,8],[4,5,8],[5,9,8]]])
for i in np.nditer(x):
    print(i)

2
3
4
6
7
8
4
5
8
5
9
8


now we will iterate with different step sizes

In [33]:
x=np.array([[2,3,4],[6,7,8],[4,5,8],[5,9,8]])
for i in np.nditer(x[:,::2]):
    print(i)


2
4
6
8
4
8
5
8


In [34]:
x=np.array([[[2,3,4],[6,7,8],[4,5,8],[5,9,8]]])
for i in np.nditer(x[:,:,::2]):
    print(i)

2
4
6
8
4
8
5
8


joining the array just like join table in sql

In [35]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.concatenate((x,y))
print(z)

[1 2 3 4 5 6]


joining the 2-d array along with rows(axis-1)
this will join the array according to the similiar column


In [36]:
x=np.array([[1,2],[3,4]])
y=np.array([[4,5],[6,7]])
z=np.concatenate((x,y),axis=1)
print(z)

[[1 2 4 5]
 [3 4 6 7]]


joining the array using the stack function: this will join the two different array according to its index 

In [37]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.stack((x,y),axis=1)
print(z)

[[1 4]
 [2 5]
 [3 6]]


stacking along with rows:hstack()

In [38]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.hstack((x,y))
print(z)

[1 2 3 4 5 6]


stacking along with coloumn:vstack()

In [39]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.array([7,8,9])
v=np.vstack((x,y,z))
print(v)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


stacking along height(depth)

In [40]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.array([7,8,9])
v=np.dstack((x,y,z))
print(v)

[[[1 4 7]
  [2 5 8]
  [3 6 9]]]


spliting array in numpy-it is reverse to joining ,breaking the array 
arrray_split()
we will split the array into 3 parts
it can automatically divide the array into its part

In [41]:
x=np.array([1,2,3,4,5,6])
y=np.array_split(x,3)
print(y)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [42]:
x=np.array([1,2,3,4,5,6])
y=np.array_split(x,4)
print(y)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [43]:
x=np.array([1,2,3,4,5,6])
y=np.array_split(x,3)
print(y)
print(y[0])
print(y[1])
print(y[2])

[array([1, 2]), array([3, 4]), array([5, 6])]
[1 2]
[3 4]
[5 6]


In [44]:
x=np.array([[1,2],[3,4],[5,6],[7,8],[12,45],[78,12]])
y=np.array_split(x,3)
print(y)
print(y[0])
print(y[1])
print(y[2])

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[12, 45],
       [78, 12]])]
[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[12 45]
 [78 12]]


spiting of 2-d array into threee 2-d along with rows

In [45]:
x=np.array([[1,2],[3,4],[5,6],[7,8],[12,45],[78,12]])
y=np.array_split(x,3,axis=1)
print(y)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [12],
       [78]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [45],
       [12]]), array([], shape=(6, 0), dtype=int32)]


alternate solution is using the hsplit(),opposite hstack()
hsplit-is dividing the arrays into horizontally which means the column wise

In [46]:
x=np.array([[1,2],[3,4],[5,6],[7,8],[12,45],[78,12]])
y=np.hsplit(x,2)
print(y)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [12],
       [78]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [45],
       [12]])]


using the where clause we can get the particular indexes of the number like where(x==1) this will give us the exact locations of the 1 inside the main array

In [47]:
x=np.array([1,2,3,4,5,6,1,3,4,1])
y=np.where(x==1)
print(y)

(array([0, 6, 9], dtype=int64),)


now we will find the indexes where the values are even

In [48]:
x=np.array([1,2,3,4,5,6,1,3,4,1])
y=np.where(x%2==0)
print(y)


(array([1, 3, 5, 8], dtype=int64),)


to find the odd

In [49]:
x=np.array([1,2,3,4,5,6,1,3,4,1])
y=np.where(x%2!=0)
print(y)

(array([0, 2, 4, 6, 7, 9], dtype=int64),)


Searchsorter()-perform binary search in array
we will now find the index where the value 7 exists it will return the index

In [14]:
x=np.array([1,2,3,4,5,6])
y=np.searchsorted(x,5)
print(y)

4


In [15]:
x=np.array([1,2,3,4,5,6,1,3,4,1])
y=np.searchsorted(x,1)
print(y)

0


now we will search from right

In [21]:
x=np.array([1,2,3,4,5,2])
y=np.searchsorted(x,5,side='right')
print(y)

6


to insert values according to the sorted and correct index order 

In [24]:
x=np.array([1,3,5,7])
y=np.searchsorted(x,[2,4,6])
print(y)

[2 2 3]


here 123 are the indexes where the values like 2 4 6 can be inserted if we want to insert then into the array

sort()-this function is used in ndarray object and this will sort a specified array

In [54]:
x=np.array([6,4,7,2,8,1,4])
print(np.sort(x))

[1 2 4 4 6 7 8]


sorting alphabatically

In [55]:
x=(['harsh','raj','mayank','ayush'])
print(np.sort(x))

['ayush' 'harsh' 'mayank' 'raj']


sorting of the 2d array

In [56]:
x=([[4,5,2],[49,34,85]])
print(np.sort(x))

[[ 2  4  5]
 [34 49 85]]


if we want the ans in one liner then join the two arrays and then apply sort function

filtering of the array
taking some element out of the existing array and creating a new array is called filtering 
a boolean index list is a list of boolean corresponding to indexes in the array (true and false)
create a array from the element on index 0 to 2

In [57]:
x=np.array([41,42,43,44])
y=[True,False,True,False]
#now we will assign the bollean list to the x array to the index wise
z=x[y]
print(z)
#the reason of output which is 41 and 43 is because they are assigned as true

[41 43]


now we will create a filter array


In [58]:
x=np.array([41,42,43,44])
emptyx=[]
#we need to provide the values which is greter then 42 
#inside the empty array
for i in x:
    if(i>42):
        emptyx.append(True)
    else:
        emptyx.append(False)

y=x[emptyx]
print(emptyx)
print(y)

[False, False, True, True]
[43 44]


we will create a filter array which will print the even numbers

In [59]:
x=np.array([1,2,3,4,5,6,7,8])
emptyx=[]

for i in x:
    if(i%2==0):
        emptyx.append(True)
    else:
        emptyx.append(False)

y=x[emptyx]
print(emptyx)
print(y)

[False, True, False, True, False, True, False, True]
[2 4 6 8]


we can also create filter directly from arrya 
that will return only values higher than 42

In [60]:
x=np.array([41,42,43,44])
y=x>42
z=x[y]
print(y)
print(z)

[False False  True  True]
[43 44]


In [25]:
x=np.array([1,2,3,4,5,6,7,8])
emptyx=x%2==0
y=x[emptyx]
print(emptyx)
print(y)

[False  True False  True False  True False  True]
[2 4 6 8]
