In [1]:
import numpy as np

random meaning something that cannot be pridicted logically
now we will generate the random number

we can import random sub library from numpy

In [2]:
from numpy import random

In [3]:
x=random.randint(100)
print(x)

4


using default rand() it will select the value between 0 to 1

In [4]:
x=random.rand()
print(x)

0.17793371666913782


we can also generate random array
we will generate a 1-d array containing 5 random number between 0 to 100

In [5]:
x=random.randint(100,size=(5))
print(x)

[23 80 87 65 31]


we will generate a 2-d array with 3 rows,each row containing 5 random int from 0 to 100

In [6]:
x=random.randint(100,size=(3,5))
print(x)

[[10 83 60 34 75]
 [29 78 56 88 31]
 [53 56 84 37 76]]


we can also generate random array
we will generate a 1-d array containing 5 random number between 0 to 100 float

In [7]:
x=random.rand(5)
print(x)

[0.66065934 0.20633128 0.27243991 0.13913038 0.98992311]


we can generate random numbers from an array 
choice()

In [8]:
x=random.choice([4,5,3,2,8,45,65])
print(x)
#this will pick the values from inside the given choice

65


we can generate random numbers from an 2-d array 
choice()

In [9]:
x=random.choice([4,5,3,2,8,45,65],size=(3,5))
print(x)

[[65  4  3  4 45]
 [ 4 45 45  8  8]
 [ 5 65  3  5  3]]


data distribution is a list of all possible value and how ofter each value occur
such lists are important when working with statistics and data science

Random distribution : probability function.

now we will generate 1-d array with 100 values where each value hass to be 3,5,7,9
the probability for the value 3 is set to be 0.1
the probability for the value 3 is set to be 0.3
the probability for the value 3 is set to be 0.6
the probability for the value 3 is set to be 0
such that their overall probability comes to be 1
p= is used for probability

In [10]:
x=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0],size=(100))
print(x)

[7 7 7 5 3 3 7 5 7 5 3 7 3 3 7 3 7 7 7 5 7 5 7 5 5 7 3 5 5 7 5 7 7 3 7 7 7
 7 3 7 5 7 3 3 5 7 5 5 7 7 7 5 7 7 3 7 7 5 5 7 7 7 7 7 5 7 5 7 7 3 5 7 5 7
 3 7 7 7 5 7 7 7 7 7 7 5 3 7 5 7 7 7 7 7 7 5 3 7 7 7]


we will generate 2-d array with 3 rows and 5 coulumn

In [11]:
x=random.choice([3,5,7,9],p=[0.1,0.3,0.6,0],size=(3,5))
print(x)

[[7 7 5 7 7]
 [7 5 7 5 5]
 [7 7 5 5 5]]


permutation of random arrays.
numpy provides 2 methods :-1 shuffle()
2-permutation()
now we will randomlu shuffle elements for the below array
shuffle()-function makes changes to the original array
permutation()-

In [4]:
x=np.array([1,2,3,4,5])
random.shuffle(x)
print(x)

[3 2 4 5 1]


permutation()-does not change the actual array it only changes the copy of the arrray

In [6]:
x=np.array([1,2,3,4,5])
y=random.permutation(x)
print(y)
print(x)

[2 1 5 4 3]
[1 2 3 4 5]
