a set is a collection of the unique element 
for creating the set we use numpy unique to find the unique elements from any array

In [1]:
import numpy as np

In [2]:
x=np.array([1,1,1,1,2,2,3,3])
y=np.unique(x)
print(y)

[1 2 3]


to find the unique values of the two 1-d array we will use the union by union1d() method

In [3]:
x=np.array([1,2,3,4])
y=np.array([3,4,5,6])
z=np.union1d(x,y)
print(z)

[1 2 3 4 5 6]


to find the values that are present on both the array using the intersection method between two array intersect1d() method

In [4]:
x=np.array([1,2,3,4])
y=np.array([3,4,5,6])
#assume unique will help the compiler to understand that no 
#repetative values in each arrray such that it make computation
#faster and efficienct
z=np.intersect1d(x,y,assume_unique=True)
print(z)

[3 4]


to find the only values that are in 1st set and not present in the 2 nd set :use setdiff1d() method

In [6]:
x=np.array([1,2,3,4])
y=np.array([3,4,5,6])
z=np.setdiff1d(x,y,assume_unique=True)
print(z)

[1 2]


to find the value that are not present in both sets we will use setxor1d()method

it is basically the !intersection - not of intersection

In [7]:
x=np.array([1,2,3,4])
y=np.array([3,4,5,6])
z=np.setxor1d(x,y)
print(z)

[1 2 5 6]
