trigonometric fun-numpy provides the unfuncs line sin(),cos(),tan() that takes values in radians and produce the corresponding sin ,cos,tan values
here now we will find the sin value of pi/2

In [1]:
import numpy as np

In [2]:
x=np.sin(np.pi/2)
print(x)

1.0


In [3]:
x=np.array([np.pi/2,np.pi/3,np.pi/4,np.pi/5])
y=np.sin(x)
print(y)

[1.         0.8660254  0.70710678 0.58778525]


we can convert degree into radians :by default all of the trigonometric functions are in radians we can thus convert then into degree 
note:radians values are pi/180 degree values
here we will convert all teh array values to radians

In [5]:
x=np.array([90,100,270,360])
y=np.deg2rad(x)
print(y)

[1.57079633 1.74532925 4.71238898 6.28318531]


now converting radians into degree

In [6]:
x=np.array([np.pi/2,np.pi,1.5*np.pi,2*np.pi])
y=np.rad2deg(x)
print(y)

[ 90. 180. 270. 360.]


we can also find angles: arcsin(),arccos(),arctan()
arc is the inverse of the sin cos or tan values
 that takes values in radians and produce the corresponding sin ,cos,tan values

we will now find angle of 1.0
the value of sin(1-radian) is 1.570 degree which is (pi/180)*90=1.570

In [2]:
x=np.arcsin(1.0)
print(x)

1.5707963267948966


angles of each values in an array

In [3]:
x=np.array([1,-1,0.1]) # need to find the degree corresponding
# to these angles
y=np.arcsin(x)
print(y)


[ 1.57079633 -1.57079633  0.10016742]


here we can also find the hypotenous using the pythagoras theorem in numpy using hypot() function
here we will find the hypot for the 4 base and 3 perpendicular

In [4]:
base=3
perp=4
x=np.hypot(base,perp)
print(x)

5.0
