zipf -

ufunc-stands for universal function and they are actually numpy functions that operates on ndarray objects

unfun also takes addition arguments like,where,dtype,out

vectorization-converting the iterative statemets into a vector
based statement

example-without ufunc here we will use python inbuilt zip()

In [7]:
x=[1,2,3,4]
y=[4,5,6,7]
z=[]
for i, j in zip(x,y):
    z.append(i+j)
print(z)    


[5, 7, 9, 11]


with ufunc , we will now use add() function

In [9]:
import numpy as np
x=[1,2,3,4]
y=[4,5,6,7]
z=np.add(x,y)
print(z)

[ 5  7  9 11]


create our own ufunc-we have to define function like we do in normal function in python then add it to the numpy function with frompyfunc() method

arguments of frompyfunc(): function,inputs,outputs
frompyfun(function name,total number of arrays as input,output in n dimension array)

creating oun ufunc for adddition

In [12]:
def myadd(x,y):
    return x+y
myadd=np.frompyfunc(myadd,2,1)
print(myadd([1,2,3,4],[5,6,7,8]))


[6 8 10 12]


check whether the func is ufunc or not

In [13]:
print(type(np.add))

<class 'numpy.ufunc'>


concatenate()-

In [14]:
print(type(np.concatenate))

<class 'numpy._ArrayFunctionDispatcher'>


unfun also takes addition arguments like,where,dtype,out

to find quotient and remainder at the same time use 
np.divmod(arr1,arr2)

to convert the negative value into positive using absolute function 

In [16]:
x=np.array([-1,-2,-3,-4,-5])
y=np.absolute(x)
print(y)

[1 2 3 4 5]


rounding decimal:there are 5 ways of rounding offf the decimal in numpy: truncation ,fix,rounding,floor,ceil
truncation:truc() and fix()
here we are truncating the below array ,these command remove the decimals and returns the float number closest to zero


In [18]:
x=np.trunc([-1.23,1.24])
print(x)

[-1.  1.]


In [19]:
x=np.fix([-1.23,1.24])
print(x)

[-1.  1.]


rounding : the around() func increments peceding digit or decimal by nearest to 1: if n>5=1 or n<5=0

In [21]:
x=np.around(3.14544,2)
#here 2 represents the upto which decimal place the output lies
print(x)

3.15


floor()-it round off decimals to the lower integer

In [23]:
x=np.floor([-3.1666,3.1444])
#here the values which is just smaller then the current value
#got printed like -4 is smaller then -3.1666 and 3 is smaller then 3.1444
print(x)

[-4.  3.]


ceil()-round off decimals to the upper integer

In [24]:
x=np.ceil([-3.1666,3.1444])
#here the values which is just greater then the current value
#got printed like -3 is smaller then -3.1666 and 4 is greater then 3.1444
print(x)

[-3.  4.]


summation-difference :addition is done b/w two ele where summation occur b/w over n elements

first we will add the list

In [25]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.add(x,y)
print(z)


[5 7 9]


now we will apply the sum() on two arrays

In [28]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.sum([x,y])
print(z)
#first it will add elements of each array and then add with other array elelment 



21


summation over an axis: if you specify axis=1 ,numpy will sum the number in each array

In [29]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=np.sum([x,y],axis=1)
print(z)

[ 6 15]


cummulative sum :means partially adding the element in array
example: [1,2,3,4] would be  [1,1+2,1+2+3,1+2+3+4]

In [30]:
x=np.array([1,2,3])
y=np.cumsum(x)
print(y)

[1 3 6]


product :use of prod() function 
here we will find the product of the element of the below arrray

In [ ]:
x=np.array([1,2,3])
y=np.prod(x)
print(y)

herer we will find the product of the 2-d array

In [32]:
x=np.array([1,2,3])
y=np.array([4,5,6])
#1*2*3*4*5*6=720
z=np.prod([x,y])
print(z)

720


what if take in axis =1
it will perform line wise product

In [33]:
x=np.array([1,2,3])
y=np.array([4,5,6])

z=np.prod([x,y],axis=1)
print(z)

[  6 120]


cummulative product :means partially product the element in array
example: [1,2,3,4] would be  [1,1*2,1*2*3,1*2*3*4]
using cumpro()

In [35]:
x=np.array([1,2,3,4,5,6])
y=np.cumprod(x)
print(y)

[  1   2   6  24 120 720]


difference : using diff() function
example: [1,2,3,4] the discrete difference of this would be 
[2-1,3-2,4-3]=[1,1,1] by using diff()

In [37]:
x=np.array([1,2,8,4,5,7,10])
y=np.diff(x)
print(y)

[ 1  6 -4  1  2  3]


to find the lcm of the array
here we will find the lcm of the 2 numbers :


In [39]:
x=4
y=8
z=np.lcm(x,y)
print(z)

8


find in array lcm
the reduce() method will use the unfunc in this case the lcm()
function on each element and it will reduce the array by 1 dimension


In [40]:
x=np.array([3,6,9])
y=np.lcm.reduce(x)
#if we dont use reduce then the ans will be (3,6,18)-which is
#it will first find lcm in 3 then in 3,6 then in 3,6,9
print(y)

18


here we will find lcm of an array wherer the array contains all integers from 1 to 10

In [41]:
x=np.arange(1,11)
y=np.lcm.reduce(x)
print(y)

2520


greatest common denominator(GCD) also knoen as hcf


In [43]:
x=6
y=9
z=np.gcd(x,y)
print(z)

3


gdc in an array

In [45]:
x=np.array([3,6,9,36])
y=np.gcd.reduce(x)
#if we dont use reduce then the ans will be (3,6,18)-which is
#it will first find lcm in 3 then in 3,6 then in 3,6,9
print(y)

3
