when we divide the train/test method into partion of 70+30 then sometimes it is possible that hte 30% of data which we are using for testing does not fits(resembles) data model which we trained so we use k fold cross validation technique

ho sakta hai ki 30% of data bache hue 70% se alag ho tabh jo model apan ne train kiya hai wo capable nahi hoga exact result generate karne ke liye tabh apan k fold ka use karnege

In [1]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
digits=load_digits()

In [2]:
from sklearn.model_selection import train_test_split
x_tain,x_test,y_train,y_test=train_test_split(digits.data,digits.target,test_size=0.3)
 

here we perform every type of training technique possible and store their score after training model to find final results using the average of all these scores

In [3]:
lr=LogisticRegression()
lr.fit(x_tain,y_train)
lr.score(x_test,y_test)

c:\vscode\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9722222222222222

In [4]:
svm=SVC()
svm.fit(x_tain,y_train)
svm.score(x_test,y_test)


0.9851851851851852

In [6]:
rf=RandomForestClassifier()
rf.fit(x_tain,y_train)
rf.score(x_test,y_test)

0.9740740740740741

In [16]:
from sklearn.model_selection import KFold
kf=KFold(n_splits=3)
print(kf)


KFold(n_splits=3, random_state=None, shuffle=False)


In [17]:
for train_index,test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index,test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


above ,the train_index is the 70% and the test_index Is 30%
and after every iteration it changes , where total iterations as 3

In [10]:
def get_score(model,x_tain,x_test,y_train,y_test):
    model.fit(x_tain,y_train)
    return model.score(x_test,y_test)
    

in above we have created the function,which insted of framing every model seperately we can call the get_score method to know the score of every mdoel seperately

In [11]:
get_score(LogisticRegression(),x_tain,x_test,y_train,y_test)

c:\vscode\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


0.9722222222222222

In [12]:
get_score(SVC(),x_tain,x_test,y_train,y_test)

0.9851851851851852

now we use k fold method 

In [13]:
from sklearn.model_selection import StratifiedKFold
folds=StratifiedKFold(n_splits=3)

In [ ]:
scores_l=[]
scores_svm=[]
scores_rf=[]

for train_index,test_index in kf.split(digits.data):
    x_tain,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],\
    digits.target[train_index],digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(),x_tain,x_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),x_tain,x_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(),x_tain,x_test,y_train,y_test))





    

In [22]:
print(scores_l)

[0.9232053422370617, 0.9415692821368948, 0.9148580968280468]


In [23]:
print(scores_svm)

[0.9666110183639399, 0.9816360601001669, 0.9549248747913188]


In [24]:
print(scores_rf)

[0.9365609348914858, 0.9499165275459098, 0.9282136894824707]


sklearn library has inbuilt function to perform all these
scores_l=[]
scores_svm=[]
scores_rf=[]

for train_index,test_index in kf.split(digits.data):
    x_tain,x_test,y_train,y_test=digits.data[train_index],digits.data[test_index],\
    digits.target[train_index],digits.target[test_index]
    scores_l.append(get_score(LogisticRegression(),x_tain,x_test,y_train,y_test))
    scores_svm.append(get_score(SVC(),x_tain,x_test,y_train,y_test))
    scores_rf.append(get_score(RandomForestClassifier(),x_tain,x_test,y_train,y_test))

using cross_val method

In [30]:
from sklearn.model_selection import cross_val_score


In [31]:
cross_val_score(LogisticRegression(),digits.data,digits.target,cv=3)


c:\vscode\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\vscode\myenv\Lib\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimiz

array([0.92153589, 0.94156928, 0.91652755])