this is the raw detailed png showing how the neuron works

to understanding the concept of gradientt descent watch the video 3blue1white

https://raw.githubusercontent.com/codebasics/deep-learning-keras-tf-tutorial/0981fe55db7a7abf19ff1d852d9a59153289641e/6_gradient_descent/nn.png

In [4]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline

In [5]:
df=pd.read_csv("insurance_data.csv")
df.head()

age  affordibility  bought_insurance
0   22              1                 0
1   25              0                 0
2   47              1                 1
3   52              0                 0
4   46              1                 1

In [6]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(df[['age','affordibility']],df.bought_insurance,test_size=0.2,random_state=25)

to convert the age into scaled data

In [7]:
x_train_scaled=x_train.copy()
x_train_scaled['age']=x_train_scaled['age']/100


x_test_scaled=x_test.copy()
x_test_scaled['age']=x_test_scaled['age']/100


here 1 represent the 1 neuron in the second layer
and the input_shape represent the 2 input neuron in the first layer which represent the age and affordibility
kernel_initializers= it represents the weight(w1,w2) initially for both neurons 

optimizer= it represnts the technique which would help our funciton to reach the global minimum

loss=it is the function which help us the reduce the losses in our model using the optimizer here it uses the log_loss function / binary_crossentropy



In [38]:
model=keras.Sequential([
    keras.layers.Dense(1,input_shape=(2,),activation='sigmoid',kernel_initializer='ones',bias_initializer='zeros')
])
model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)
model.fit(x_train_scaled,y_train,epochs=5000)

c:\vscode\myenv\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Epoch 1/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 2s 2s/step - accuracy: 0.5000 - loss: 0.7113
Epoch 2/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 82ms/step - accuracy: 0.5000 - loss: 0.7110
Epoch 3/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 71ms/step - accuracy: 0.5000 - loss: 0.7106
Epoch 4/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 76ms/step - accuracy: 0.5000 - loss: 0.7102
Epoch 5/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5000 - loss: 0.7098
Epoch 6/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 70ms/step - accuracy: 0.5000 - loss: 0.7094
Epoch 7/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0.5000 - loss: 0.7091
Epoch 8/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.5000 - loss: 0.7087
Epoch 9/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 75ms/step - accuracy: 0.5000 - loss: 0.7083
Epoch 10/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 78ms/step - accuracy: 0.5000 - loss: 0.7079
Epoch 11/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 69ms/step - accuracy: 0.5000 - loss: 0.7076
Epoch 12/5000
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 67ms/step - accuracy: 0

instead of accuracy we use the evaluate in tensorflow

In [39]:
model.evaluate(x_test_scaled,y_test)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 339ms/step - accuracy: 1.0000 - loss: 0.3550


[0.3549776077270508, 1.0]

In [21]:
model.predict(x_test_scaled)

NameError: name 'model' is not defined

In [22]:
y_test

2     1
10    0
21    0
11    0
14    1
9     1
Name: bought_insurance, dtype: int64

now to get the weight and bias 

In [23]:
coef, intercept=model.get_weights()

NameError: name 'model' is not defined

In [24]:
coef,intercept

NameError: name 'coef' is not defined

This means w1=3.3667657, w2=1.195381, bias =-2.0199888

now we will create our own neuron and prediction layer function

writing sigmoid function

In [20]:
def sigmoid(x):
    import math
    return 1/(1+math.exp(-x))

#example
sigmoid(18)

0.9999999847700205

In [45]:
x_test

age  affordibility
2    47              1
10   18              1
21   26              0
11   28              1
14   49              1
9    61              1

Instead of model.predict, write our own prediction function that uses w1,w2 and bias

the above we have extracted the coef which contains the w1 and w2 compatible for the 90% accurate model by neuron 
the extractaction of the intercept above can be used below as we have already collected as bias

we will use the age input as age/100 because we are using the scaled value according to the trained bias and weights

In [19]:
def prediction_function(age,affordibility):
    weighted_sum=coef[0]*age+coef[1]*affordibility+intercept
    return sigmoid(weighted_sum)

prediction_function(.47,1)

NameError: name 'coef' is not defined

In [47]:
prediction_function(.18,1)

C:\Users\ayush\AppData\Local\Temp\ipykernel_1208\2218631885.py:3: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  return 1/(1+math.exp(-x))


0.35569571637887243

Now we start implementing gradient descent in plain python. Again the goal is to come up with same w1, w2 and bias that keras model calculated. We want to show how keras/tensorflow would have computed these values internally using gradient descent

First write couple of helper routines such as sigmoid and log_loss

In [11]:
def sigmoid_numpy(x):
    return 1/(1+np.exp(-x))

sigmoid_numpy(np.array([12,0,1]))

array([0.99999386, 0.5       , 0.73105858])

to reduce our losses we use the log_loss

In [28]:
def log_loss(y_true,y_predicted):
    epsilon=1e-15
    y_predicted_new=[max(i,epsilon) for i in y_predicted]
    y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new=np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

All right now comes the time to implement our final gradient descent function !! yay !!!

here we set the values of w1 and w2 as 1 and bias=0 and the learning_rate as 0.5

In [32]:
def gradient_descent(age,affordibility,y_true,epochs,loss_threshold):
    w1=w2=1
    bias=0
    rate=0.5
    n=len(age)
    for i in range(epochs):
        weighted_sum=w1*age+w2*affordibility+bias
        y_predicted=sigmoid_numpy(weighted_sum)
        loss=log_loss(y_true,y_predicted)
#for calculating the new w1 and w2 we first need to find the partial derivative of the slope of the function so as to adjust the global minimum
#This is the gradient of the loss function with respect to the parameter w1
#It measures the rate of change of the loss function with respect to w1
#The gradient points in the direction of the steepest increase in the loss function, so subtracting it moves the parameter in the direction that decreases the loss.
        w1d=(1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
        w2d=(1/n)*np.dot(np.transpose(affordibility),(y_predicted-y_true))

#now to update the w1 and w2 after the loss calcualtion and to readjust weights to reduce loss
#using the formula w1=w1-learning rate * d/dw1
        #the updated values are after the loss calculattion
        bias_d=np.mean(y_predicted-y_true)
        w1=w1-rate*w1d
        w2=w2-rate*w1d
        bias=bias-rate*bias_d

        print(f'epochs:{i},w1:{w1},w2:{w2},bias:{bias},loss:{loss}')
#the threshold value will tell us to when to stop after finding correct parametes
        if loss<=loss_threshold:
            print(f'Loss threshold reached. Stopping training.')
            break

    return w1,w2,bias

In [35]:
gradient_descent(x_train_scaled['age'],x_train_scaled['affordibility'],y_train,5000,0.4631)

epochs:0,w1:0.974907633470177,w2:0.974907633470177,bias:-0.11341867736368583,loss:0.7113403233723417
epochs:1,w1:0.9550221702595474,w2:0.9550221702595474,bias:-0.2136863103960515,loss:0.683558895116285
epochs:2,w1:0.9399181456567614,w2:0.9399181456567614,bias:-0.301924150074239,loss:0.6623475259348045
epochs:3,w1:0.9291098513704422,w2:0.9291098513704422,bias:-0.37938388824209784,loss:0.6463188645180143
epochs:4,w1:0.9220922997184198,w2:0.9220922997184198,bias:-0.44734835727785316,loss:0.6342689529820928
epochs:5,w1:0.9183719797959894,w2:0.9183719797959894,bias:-0.5070587145874558,loss:0.6252081924070263
epochs:6,w1:0.9174870146355725,w2:0.9174870146355725,bias:-0.5596680263382398,loss:0.6183561635588656
epochs:7,w1:0.9190183411617726,w2:0.9190183411617726,bias:-0.6062166544697184,loss:0.6131164279712223
epochs:8,w1:0.9225942303620167,w2:0.9225942303620167,bias:-0.6476234928849,loss:0.6090437822850325
epochs:9,w1:0.9278903613703289,w2:0.9278903613703289,bias:-0.6846875705903542,loss:0.6

(25.393517244934515, 25.393517244934515, -31.605348392759044)

In [69]:
coef,intercept

(array([[5.060863 ],
        [1.4086521]], dtype=float32),
 array([-2.913703], dtype=float32))

-----------------------------------------------------

whole cnn manually

we will now create the whole neural network from begining to end

In [29]:
class mynn():
    def __init__(self):
        self.w1=1
        self.w2=1
        self.bias=0

    def fit(self,x,y,epochs,loss_threshold):
        self.w1,self.w2,self.bias=self.gradient_descent(x['age'],x['affordibility'],y,epochs,loss_threshold)
        print(f'final weights and bias: w1: {self.w1},w2:{self.w2},bias:{self.bias}')

    def sigmoid_numpy(x):
        return 1/(1+np.exp(-x))
    
    def log_loss(y_true,y_predicted):
        epsilon=1e-15
        y_predicted_new=[max(i,epsilon) for i in y_predicted]
        y_predicted_new=[min(i,1-epsilon) for i in y_predicted_new]
        y_predicted_new=np.array(y_predicted_new)
        return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))
    
    def predict(self,x_test):
        weighted_sum=self.w1*x_test['age']+self.w2*x_test['affordibility']+self.bias
        return sigmoid_numpy(weighted_sum)
    
    def gradient_descent(self,age,affordibility,y_true,epochs,bias_threshold):
        w1=w2=1
        bias=0
        rate=0.5
        n=len(age)
        for i in range(epochs):
            weighted_sum=w1*age+w2*affordibility+bias
            y_predicted=sigmoid_numpy(weighted_sum)
            loss=log_loss(y_true,y_predicted)
    
            w1d=(1/n)*np.dot(np.transpose(age),(y_predicted-y_true))
            w2d=(1/n)*np.dot(np.transpose(affordibility),(y_predicted-y_true))

   
            bias_d=np.mean(y_predicted-y_true)
            w1=w1-rate*w1d
            w2=w2-rate*w1d
            bias=bias-rate*bias_d

            if i%50==0:
                print(f'epochs:{i},w1:{w1},w2:{w2},bias:{bias},loss:{loss}')
                
            if bias<=bias_threshold:
                print (f'Epoch:{i}, w1:{w1}, w2:{w2}, bias:{bias}, loss:{loss}')
                break
                
                

        return w1,w2,bias
        


In [30]:
custommodel=mynn()
custommodel.fit(x_train_scaled,y_train,epochs=8000,loss_threshold=0.4631)

epochs:0,w1:0.974907633470177,w2:0.974907633470177,bias:-0.11341867736368583,loss:0.7113403233723417
Epoch:0, w1:0.974907633470177, w2:0.974907633470177, bias:-0.11341867736368583, loss:0.7113403233723417
final weights and bias: w1: 0.974907633470177,w2:0.974907633470177,bias:-0.11341867736368583


In [31]:
custommodel.predict(x_test_scaled)

2     0.789131
10    0.738265
21    0.534957
11    0.756662
14    0.792357
9     0.810948
dtype: float64