In [1]:
import numpy as np

we are trying to perform operations on matrixes using the numpy modules and methodology over 2-d arrray

here revenue and expenses are the 2-d matrix which contains columns of 2018,2019,2020

In [6]:
revenue=np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses=np.array([[80,90,100],[10,16,20],[8,10,10]])

now to find the profit or loss amongst these 3years we need to perform subtraction over revenue-expencse on matrixes

In [7]:
profit=revenue-expenses
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

now we got matrix which is columns are=iphone,ipad,mac
price_per[1000,400,1200]  and the
 units([30,40,50],[5,10,15],[2,5,7])
now we have to perform the matrix multiplication where we will multiply ppy(1-row,3column) with units(3-rows ,3 columns)
to per this operation numpy use broadcasting technique where it will automatically expand the ppy matrix three times and multiply with every row one time

In [9]:
price_per=np.array([1000,400,1200])
units=np.array([[30,40,50],[5,10,15],[2,5,7]])
price_per*units

array([[30000, 16000, 60000],
       [ 5000,  4000, 18000],
       [ 2000,  2000,  8400]])

but to find the total sales every year of
 price_per*(iphone)+price_per*(ipad)+price_per*(mac)
we need to perfom dot product


In [10]:
np.dot(price_per,units)

array([34400, 50000, 64400])